# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ol75"
  config.vm.box_url = 'https://yum.oracle.com/boxes/oraclelinux/ol75/ol75.box'

  config.vm.box_check_update = false

  [
    { :name => "vagrant-reload",  :version => ">= 0.0.1" },
    { :name => "vagrant-vbguest", :version => ">= 0.15.0"}
  ].each do |plugin|
    Vagrant::Plugin::Manager.instance.installed_specs.any? do |s|
      req = Gem::Requirement.new([plugin[:version]])
      if (not req.satisfied_by?(s.version)) && plugin[:name] == s.name
        puts "Installing #{plugin[:name]} Plugin..."
        system("vagrant plugin install #{plugin[:name]}")
      end
    end
  end

  config.vm.provider "virtualbox" do |vb|
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end

  config.vm.network "forwarded_port", guest: 2375, host: 2375

  config.vm.provision "shell", inline: <<-SHELL
    yum -y update
    yum -y install docker-engine git go graphviz
    wipefs -a /dev/sdb
    echo 'DOCKER_STORAGE_OPTIONS= --storage-driver=devicemapper --storage-opt dm.directlvm_device="/dev/sdb"' >> /etc/sysconfig/docker-storage
    sed -e '\\|OPTIONS=|s|.*|OPTIONS=--selinux-enabled --debug -H tcp://0.0.0.0:2375 -H unix://|g' -i /etc/sysconfig/docker
    systemctl enable docker.service
    systemctl daemon-reload
    systemctl start docker
    systemctl status docker
    usermod -aG docker vagrant
    yum clean all
    rm -rf /var/cache/yum
  SHELL

  config.vm.provision :reload
end
